# Generated by Django 3.2.6 on 2021-09-15 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curation', '0003_curation_pub_date'),
        ('product', '0008_auto_20210915_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_tags', models.ManyToManyField(blank=True, to='curation.CurationTag')),
                ('curations', models.ManyToManyField(blank=True, to='curation.Curation')),
                ('product_tags', models.ManyToManyField(blank=True, to='product.ProductTag')),
                ('products', models.ManyToManyField(blank=True, to='product.Product')),
                ('recommend_to_user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
