# Generated by Django 3.2.6 on 2021-09-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='online_shop',
            field=models.CharField(choices=[('네이버 스마트스토어', '네이버 스마트스토어'), ('해외사이트', '해외사이트'), ('이케아', '이케아'), ('기타', '기타'), ('오늘의 집', '오늘의 집'), ('집꾸미기', '집꾸미기')], default='오늘의 집', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('장식/조명', '장식/조명'), ('가구', '가구'), ('수납/정리', '수납/정리'), ('패브릭', '패브릭'), ('가전', '가전'), ('DIY/공구', 'DIY/공구')], default='가구', max_length=20),
        ),
    ]
