# Generated by Django 3.2.6 on 2021-09-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_Type',
            field=models.CharField(choices=[('오프라인', '오프라인'), ('비매품', '비매품'), ('온라인', '온라인')], default='온라인', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('수납/정리', '수납/정리'), ('가전', '가전'), ('장식/조명', '장식/조명'), ('DIY/공구', 'DIY/공구'), ('패브릭', '패브릭'), ('가구', '가구')], default='가구', max_length=20),
        ),
    ]
