# Generated by Django 3.2.6 on 2021-09-06 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210906_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop_Type',
            field=models.CharField(choices=[('비매품', '비매품'), ('온라인', '온라인'), ('오프라인', '오프라인')], default='온라인', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('DIY/공구', 'DIY/공구'), ('수납/정리', '수납/정리'), ('패브릭', '패브릭'), ('가전', '가전'), ('장식/조명', '장식/조명'), ('가구', '가구')], default='가구', max_length=20),
        ),
    ]
