# Generated by Django 3.2.6 on 2021-09-29 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapproduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrapcuration',
            name='curation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapuser', to='curation.curation'),
        ),
        migrations.AddField(
            model_name='scrapcuration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapcuration', to=settings.AUTH_USER_MODEL),
        ),
    ]
