# Generated by Django 3.2.6 on 2021-09-23 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_auto_20210923_1116'),
        ('scrap', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapcuration',
            name='curation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapuser', to='curation.curation'),
        ),
        migrations.AlterField(
            model_name='scrapcuration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapcuration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrapproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapuser', to='product.product'),
        ),
        migrations.AlterField(
            model_name='scrapproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapproduct', to=settings.AUTH_USER_MODEL),
        ),
    ]
