# Generated by Django 3.2.6 on 2021-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210901_0148'),
        ('curation', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment_curation',
            field=models.ManyToManyField(blank=True, related_name='CommentCustomUser', to='curation.CurationComment'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comment_product',
            field=models.ManyToManyField(blank=True, related_name='CommentCustomUser', to='product.ProductComment'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_curation',
            field=models.ManyToManyField(blank=True, related_name='CreatedCustomUser', to='curation.Curation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_product',
            field=models.ManyToManyField(blank=True, related_name='CreatedCustomUser', to='product.Product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='like_curation',
            field=models.ManyToManyField(blank=True, related_name='LikeCustomUser', to='curation.Curation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='like_product',
            field=models.ManyToManyField(blank=True, related_name='LikeCustomUser', to='product.Product'),
        ),
    ]
