# Generated by Django 3.2.6 on 2021-09-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='nickname', max_length=30),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
