# Generated by Django 3.2.6 on 2021-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0003_curation_pub_date'),
        ('product', '0008_auto_20210915_2307'),
        ('users', '0005_alter_customuser_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='comment_curation',
            field=models.ManyToManyField(blank=True, related_name='CommentCustomUser', to='curation.CurationComment'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comment_product',
            field=models.ManyToManyField(blank=True, related_name='CommentCustomUser', to='product.ProductComment'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_curation',
            field=models.ManyToManyField(blank=True, related_name='CreatedCustomUser', to='curation.Curation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_product',
            field=models.ManyToManyField(blank=True, related_name='CreatedCustomUser', to='product.Product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='like_curation',
            field=models.ManyToManyField(blank=True, related_name='LikeCustomUser', to='curation.Curation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='like_product',
            field=models.ManyToManyField(blank=True, related_name='LikeCustomUser', to='product.Product'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='CustomUser', to='users.Interest'),
        ),
    ]
